# Generated by Django 3.0.8 on 2020-09-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=' ', upload_to='image/')),
                ('name', models.CharField(default=' ', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(default=' ', max_length=150)),
                ('desc', models.TextField(default=' ')),
                ('remark', models.TextField(default=' ')),
            ],
        ),
    ]
