# Generated by Django 3.0.8 on 2020-09-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('name', models.CharField(default=' ', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('addr', models.CharField(default=' ', max_length=150)),
                ('content', models.TextField(default=' ')),
                ('detail', models.TextField(default=' ')),
            ],
        ),
    ]
